### ISSUE TITLE
Recipe Queries

### ISSUE THREAD

**Issue by sydney-sisco** [sydney-sisco/bite-size#25]
Browse
GET /recipes 
Read
GET /recipes/:id
Edit
PATCH /recipes/:id
Add
POST /recipes 
Delete
DELETE /recipes/:id

**Comment by eppalea** [comment]
Done so far:
getUserEmojiReactions
getRecipes
getRecipe
getRecipeInstructions
getRecipeIngredients
getRecipeDetails
deleteSpecificRecipe

in progress:
postNewRecipe
