### ISSUE TITLE
Choose Framework

### ISSUE THREAD

**Issue by evanquirk** [sydney-sisco/bite-size#3]
### Summary
Decide which framework to go with.

### Steps:
- research...

### Outcome:
We're on the same page and have a framework picked out

**Comment by sydney-sisco** [comment]
React vs Svelte!

**Comment by evanquirk** [comment]
Are we gonna go node? Compare Express with Fastify?
(https://www.fastify.io/)

**Comment by eppalea** [comment]
choosing to venture into the unknown!
