### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by eppalea** [sydney-sisco/bite-size#60]
seed database

const items = [
    { value: 1, label: "Vegetarian" },
    { value: 2, label: "Vegan" },
    { value: 3, label: "Poultry" },
    { value: 4, label: "Seafood" },
    { value: 5, label: "Pork" },
    { value: 6, label: "Beef" },
    { value: 7, label: "Gluten-Free" },
    { value: 8, label: "Lactose-Free" },
    { value: 9, label: "Halal" },
    { value: 10, label: "Breakfast" },
    { value: 11, label: "Brunch" },
    { value: 12, label: "Lunch" },
    { value: 13, label: "Dinner" },
    { value: 14, label: "Dessert" }
]

Vegetarian
Vegan
Poultry
Seafood
Pork
Beef
Gluten-Free
Lactose-Free
Halal
Breakfast
Brunch
Lunch
Dinner
Dessert

loops through form

create a component to pass to various pages

update get recipe details function to also get recipe tags

**Comment by evanquirk** [comment]
Done done done!
